FROM cypress/included:14.4.1
ENV LANG=C.UTF-8
ENV TZ=Asia/Tokyo
WORKDIR /e2e

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y \
    vim \
    curl \
    less \
    jq \
    zip \
    unzip
RUN apt-get clean && \
    rm -rf /var/cache/apt/archives/* && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    truncate -s 0 /var/log/*log
COPY cypress/test/package*.json .
RUN npm install -g npm \
    && npm install -g npm-check-updates \
    && npm install -g typescript
RUN npm install
